[package]
name = "redbook"
description = "CDDA CD digital audio as per RedBook"
categories = ["Command line utilities", "Multimedia", "Hardware support"]
keywords = ["ccda", "windows", "flac"]
authors = ["Mike Foster <https://github.com/MusicalNinjaDad>"]
homepage = "https://github.com/MusicalNinjaDad/redbook"
repository = "https://github.com/MusicalNinjaDad/redbook"
readme = "README.md"
license = "MIT"
edition = "2024"
version = "0.1.0"

[dependencies]
cdtoc = "0.14.0"
clap = { version = "4.6.5", features = ["derive"] }
exit_safely = "0.3.1"
flacenc = { version = "0.5.1" }
humanize-duration = "0.0.7"
metaflac = "0.2.8"
musicbrainz_rs = { version = "0.14.0", features = ["sync", "native_tls"] }
reqwest = { version = "0.13.4", default-features = false, features = [
    "blocking",
    "native-tls",
    "json",
] }
serde_json = "1.0"
tabular = "0.2.0"
try_v2 = "0.10.1"
tracing = "0.1"
tracing-result = { git = "https://github.com/MusicalNinjaDad/tracing_result/" }
tracing-subscriber = { version = "0.3", features = ["fmt", "json"] }
windows-sys = { version = "0.61.2", features = [
    "Win32_Devices_Cdrom",
    "Win32_Storage",
    "Win32_Storage_FileSystem",
    "Win32_Security",
    "Win32_System",
    "Win32_System_IO",
] }
zune-jpeg = "0.5.15"

[dev-dependencies]
rstest = "0.26.1"

[build-dependencies]
build_safely = "0.5.4"
clap = { version = "4.6.5", features = ["derive"] }
clap_builder = "4.6.5"
clap_complete = "4.6.8"
clap_mangen = "0.3.0"

[workspace.metadata.ninja-xtask]
env = { "LD_LIBRARY_PATH" = false }

[lints]
# Explicitness
clippy.allow_attributes = "deny" # use expect instead
clippy.let_underscore_must_use = "deny" # use expect(unused_must_use, reason = "") instead
clippy.unused_result_ok = "deny"

# Completeness
rustc.missing_docs = "warn"

# Unsafe lints are documented at top of lib.rs for ease of auditing
