[workspace]
members = ["crates/*"]

[workspace.package]
keywords = ["ccda", "windows", "flac"]
authors = ["Mike Foster <https://github.com/MusicalNinjaDad>"]
repository = "https://github.com/MusicalNinjaDad/redbook"
edition = "2024"
version = "0.2.1"

[workspace.dependencies]
build_safely =  "0.6.0"
cdtoc = "0.14.0"
clap = { version = "4.6.5", features = ["derive"] }
clap_builder = "4.6.5"
clap_complete = "4.6.8"
clap_mangen = "0.3.0"
errno = "0.3.14"
exit_safely = "0.3.1"
flacenc = { version = "0.5.1" }
glob = "0.3.4"
humanize-duration = "0.0.7"
metaflac = "0.2.8"
musicbrainz_rs = { version = "0.14.0", features = ["sync", "native_tls"] }
proc-macro2 = "1.0.107"
reqwest = { version = "0.13.4", default-features = false, features = ["blocking", "native-tls", "json"] }
rstest = "0.26.1"
serde_json = "1.0"
similar-asserts = "2.0.0"
slint  = "1.18.0"
slint-build = "1.18.0"
syn = {version = "3.0.5", features = ["full", "extra-traits"]}
tabular = "0.2.0"
tempfile = "3.27.0"
tracing = "0.1"
tracing-result = "0.0.1"
tracing-subscriber = { version = "0.3", features = ["fmt", "json"] }
try_v2 = "0.11.0"
windows-bindgen = "0.100.0"
windows-link = "0.100.0"
zune-jpeg = "0.5.15"

[workspace.metadata.ninja-xtask]
env = { "LD_LIBRARY_PATH" = false }

[workspace.lints]
# Explicitness
clippy.allow_attributes = "deny" # use expect instead
clippy.let_underscore_must_use = "deny" # use expect(unused_must_use, reason = "") instead
clippy.let_underscore_untyped = "deny"
clippy.unused_result_ok = "deny"
clippy.used_underscore_binding = "deny"

# Safety
clippy.missing_safety_doc = "deny" # conflicts with clap derive: allow(clippy::style)
clippy.multiple_unsafe_ops_per_block = "deny" # sometimes valuable to inline calls
clippy.transmute_ptr_to_ptr = "deny" # conflicts with clap derive: allow(clippy::pedantic)
clippy.undocumented_unsafe_blocks = "deny" # auto-generated bindings
rust.unsafe_op_in_unsafe_fn = "forbid"
rust.unsafe_attr_outside_unsafe = "forbid"
rust.unused_unsafe = "deny"
