import {
    ScrollView,
    VerticalBox,
    Switch,
    HorizontalBox,
    CheckBox,
    Button,
    ProgressIndicator,
    AboutSlint,
} from "std-widgets.slint";
export struct ReleaseDetails {
    album: string,
    date: string,
    location: string,
    barcode: string,
    comment: string,
    thumbnail: image,
    id: string,
}

export struct TrackDetails {
    number: int,
    title: string,
    rip: bool = true,
}

global Sizes {
    out property <length> tile-width: 480px;
    out property <length> thumbnail: 125px;
    out property <length> spacing: 10px;
    out property <length> tile-height: thumbnail + (2 * spacing);
}

component ReleaseTile {
    in property <brush> bkg <=> box.background;
    in property <ReleaseDetails> release;
    property thumb <=> release.thumbnail;
    callback clicked <=> touch.clicked;
    box := Rectangle {
        accessible-role: AccessibleRole.list-item;
        accessible-description: release.album + " " + release.comment + ". Released on " + release.date + " in " + release.location + ", barcode: " + release.barcode;
        drop-shadow-offset-x: 0px;
        drop-shadow-offset-y: 0px;
        drop-shadow-color: darkgray;
        drop-shadow-blur: Sizes.spacing * 0.8;
        border-radius: self.drop-shadow-blur / 2;
        min-width: Sizes.tile-width;
        touch := TouchArea { }

        HorizontalLayout {
            alignment: start;
            padding: Sizes.spacing;
            thumbnail := Image {
                horizontal-alignment: left;
                width: Sizes.thumbnail;
                height: Sizes.thumbnail;
                source: thumb;
            }

            info := VerticalLayout {
                spacing: Sizes.spacing;
                padding-top: Sizes.spacing / 2;
                padding-left: Sizes.spacing * 2.5;
                alignment: start;
                name := Text {
                    text: release.album;
                    font-weight: FontWeight.semi-bold;
                    font-size: 1.5rem;
                }

                comment := Text {
                    text: release.comment;
                }

                where_when := HorizontalLayout {
                    Text {
                        text: "Released: " + release.date;
                    }

                    Text {
                        text: release.location;
                    }
                }

                barcode := Text {
                    text: "Barcode: " + release.barcode;
                }
            }
        }
    }
}

component ReleaseSelector inherits ScrollView {
    in property <[ReleaseDetails]> releases;
    in property <brush> bkg;
    callback select_release(release: ReleaseDetails);
    min-width: Sizes.tile-width + (2 * Sizes.spacing);
    min-height: Sizes.tile-height + (2 * Sizes.spacing);
    album_selector := FlexboxLayout {
        padding: Sizes.spacing * 2;
        spacing: Sizes.spacing * 2;
        cross-axis-line-alignment: start;
        for album[index] in releases: ReleaseTile {
            bkg: bkg;
            release: album;
            clicked => { select_release(album) }
        }
    }
}

component TrackListing inherits ScrollView {
    in property <brush> bkg;
    in property <ReleaseDetails> release;
    in property <[TrackDetails]> tracks;
    callback rip();
    VerticalLayout {
        padding: Sizes.spacing * 2;
        spacing: Sizes.spacing * 2;
        alignment: start;
        cross-axis-alignment: end;
        ReleaseTile {
            bkg: bkg;
            release: release;
        }

        VerticalBox {
            cross-axis-self-alignment: start;
            // TODO: #63 Reset rip true for all tracks when setting rip all
            rip_all := Switch {
                text: "Rip all";
                checked: true;
            }

            for track in tracks: HorizontalBox {
                CheckBox {
                    checked <=> track.rip;
                    enabled: !rip_all.checked;
                }

                Text {
                    text: track.number + ": " + track.title;
                    font-weight: FontWeight.semi-bold;
                    font-size: 1.25rem;
                }
            }
        }

        Button {
            text: "Rip";
            primary: true;
            clicked => { rip() }
        }
    }
}

export component MainWindow inherits Window {
    title: "rip";
    property <int> tiles: releases.length;
    property <int> prefered-cols: 2;
    property <int> prefered-rows: (tiles + 1) / prefered-cols; // rounds down
    preferred-width: (prefered-cols * Sizes.tile-width) + (2 * (prefered-cols + 1) * Sizes.spacing);
    preferred-height: (5 * Sizes.tile-height) + (2 * (prefered-rows + 1) * Sizes.spacing); // TODO: #64 Well-calculated default size
    in property <[ReleaseDetails]> releases;
    in-out property <[TrackDetails]> tracks;
    callback select_release(release: ReleaseDetails);
    callback rip();
    if releases.length > 1: ReleaseSelector {
        releases: releases;
        bkg: root.background;
        select_release(release) => { select_release(release) }
    }
    if releases.length == 1: TrackListing {
        release: releases[0];
        tracks: tracks;
        bkg: root.background;
        rip => { rip() }
    }
    if releases.length == 0: VerticalBox {
        Text {
            horizontal-alignment: center;
            vertical-alignment: center;
            font-size: 2rem;
            text: "Getting details from MusicBrainz ... ";
        }

        AboutSlint {
            cross-axis-self-alignment: end;
            max-height: 25px;
         }

        ProgressIndicator {
            height: Sizes.spacing;
            indeterminate: true;
        }
    }
}
