name: Publish to crates.io
concurrency: Crates.io

on:
  release:
    types: [published]

env:
  CARGO_TERM_COLOR: always

jobs:
  quality-check:
    uses: ./.github/workflows/rust.yml

  # # No lib publishing yet - patching musicbrainz_rs & api_bindium
  # publish_lib:
  #   needs: quality-check
  #   environment: crates.io
  #   permissions:
  #     id-token: write
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v7.0.1
  #     with:
  #       ref: ${{ github.event.release.target_commitish }}
  #   # Install manually as different crates may have custom toolchains defined
  #   - name: install rust
  #     run: rustup set profile default && rustup install
  #   # Use OIDC for updating existing crates
  #   - uses: rust-lang/crates-io-auth-action@bbd81622f20ce9e2dd9622e3218b975523e45bbe #v1.0.4
  #     id: auth
  #   - name: Publish
  #     env:
  #       CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}
  #     run:
  #       cargo publish

  binaries:
    needs:
      - quality-check
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: checkout tagged commit
        uses: actions/checkout@v7
        with:
          ref: ${{ github.event.release.target_commitish }}
      - name: create folder for package
        run: mkdir rip
      - name: install rust
        run: rustup install && rustup update && rustup target add x86_64-pc-windows-msvc
      - name: install build-tools
        uses: taiki-e/install-action@v2.86.6
        with:
          tool: cargo-xwin,cargo-about
      - name: latest msvc
        id: msvc_key
        run: |
          HASH=$(gh api repos/trcrsired/windows-msvc-sysroot/releases/latest --jq '.assets[] | select(.name == "windows-msvc-sysroot.tar.xz") | .digest' | cut -d: -f2)
          echo "key=$HASH" >> $GITHUB_OUTPUT
      - uses: actions/cache@v6.1.0
        with:
          path: /home/runner/.cache/cargo-xwin
          key: ${{ steps.msvc_key.outputs.key }}
      - name: build
        run: cargo xwin cache windows-msvc-sysroot && cargo xwin cache xwin && cargo xwin build --target x86_64-pc-windows-msvc --release
      - name: generate licenses file
        run: cargo about generate --output-file third-party-licenses.html about.hbs
      - name: create archive
        run: |
          cp LICENSE rip/
          cp third-party-licenses.html rip/
          cp README.md rip/
          cp target/x86_64-pc-windows-msvc/release/*.exe rip/
          zip -r rip.zip rip/*
      - name: upload
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release upload ${{ github.event.release.tag_name }} 'rip.zip'
