[package]
name = "redbook-rip"
description = "CD ripper"
categories = ["multimedia::audio", "hardware-support"]
keywords.workspace = true
authors.workspace = true
repository.workspace = true
license = "MIT"
edition.workspace = true
version.workspace = true
publish = false

[[bin]]
name = "rip"
path = "src/main.rs"

[dependencies]
crossbeam.workspace = true
metaflac.workspace = true
musicbrainz_rs.workspace = true
redbook.workspace = true
redbook.features = ["simd-nightly"]
slint.workspace = true
thread_safely.workspace = true
tracing.workspace = true
tracing-result.workspace = true
tracing-subscriber.workspace = true

[build-dependencies]
build_safely.workspace = true
slint-build.workspace = true
winresource = "0.1"

[lints]
workspace = true
